networks:
  haproxy1:
    driver: bridge
  haproxy2:
    driver: bridge

services:
  haproxy1:
    image: haproxy
    ports:
      - "80:80"
      - "22:22110"
      - "81:81"
      - "8080:8080"
      - "8500:8500"
      - "443:443"
    volumes:
      - ./haproxy-1/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./certs:/usr/local/etc/haproxy/certs
    networks:
      - haproxy1
      - haproxy2
    depends_on:
      - nginx1
      - nginx2
      - nginx3

  nginx1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx-1/index.html:/usr/share/nginx/html/index.html
      - ./nginx-1/jquery.js:/usr/share/nginx/html/jquery.js
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - haproxy1
      - haproxy2

  nginx2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx-2/index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - haproxy1
      - haproxy2

  nginx3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx-3/index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - haproxy1
      - haproxy2      
    